deploy from primary repository (#238)
* add deploy configuration

* remove initial check - bin/setup fails from fresh install

* add run_deploy script

* add ci workflow for deployments

* run on ubuntu

* feat: create encrypted credentials for development env when running bin/setup

* update gitignore credentials files

* update bin/setup

* commit database.yml and remove redundant gitignores

* update github actions token

* switch to self hosted runner

* add encrypted staging and production credentials

* install nix-shell in ci

* add deployment submodule

* updated keys and rails configuration

* remove submodule

* remove capistrano submodule in favour of required files

* remove nix install from deploy

* move capistrano gems to deploy group

* update Capfile path

* update installation instructions

* add whenever gem to deploy group

* add missing slack notifier

* add httparty to deploy group

* remove and revoke old deploy notification webhook

* switch to utf8 as default to match production

* fetch database.yml values from encrypted credentials

* remove more redundant cap tasks

* remove more rake tasks

* more task refactoring

* added credentials key fetch from env

* additional cap task config updates

* remove git submodules gem

* set secrets to env variables

* set back to master branch for deployments

---------

Co-authored-by: Gustavo Carvalho <gustavo.hcarvalho@outlook.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,12 +18,6 @@ jobs:
         shell: bash
         run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
         id: extract_branch
-      - run: |
-          for f in config/*.sample
-          do
-            echo "Copying $f to ${f%.*}"
-            cp $f ${f%.*}
-          done
       - name: Cache gems
         # Pin to 3.0.11 SHA
         uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
@@ -96,3 +90,84 @@ jobs:
       PGPORT: 5432
       PGPASSWORD: postgres
       RAILS_ENV: test
+
+  deploy:
+    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stable'
+    needs:
+      - build
+    defaults:
+      run:
+        shell: bash -leo pipefail {0}
+    runs-on: self-hosted
+    steps:
+      - name: Checkout branch
+        # Pin to v3.1.0 SHA
+        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
+        with:
+          submodules: true
+          token: ${{ secrets.ACTIONS_TOKEN }}
+          fetch-depth: 10
+      - name: Extract branch name and stage
+        shell: bash
+        id: extract_branch
+        run: |
+          STAGE=staging
+          if [[ "${GITHUB_REF#refs/heads/}" == "stable" ]]; then
+            STAGE=production
+          fi
+          echo "STAGE=$STAGE" >> $GITHUB_ENV
+          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
+      - name: Set secrets to environment variables
+        shell: bash
+        id: set_secrets_to_environment_variables
+        run: |
+          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
+          if [[ "${GITHUB_REF#refs/heads/}" == "stable" ]]; then
+            echo "PRODUCTION_SERVER_HOSTNAME=${{ secrets.PRODUCTION_SERVER_HOSTNAME }}" >> $GITHUB_ENV
+            echo "PRODUCTION_SERVER_USERNAME=${{ secrets.PRODUCTION_SERVER_USERNAME }}" >> $GITHUB_ENV
+            echo "RAILS_PRODUCTION_KEY=${{ secrets.RAILS_PRODUCTION_KEY }}" >> $GITHUB_ENV
+          else
+            echo "STAGING_SERVER_HOSTNAME=${{ secrets.STAGING_SERVER_HOSTNAME }}" >> $GITHUB_ENV
+            echo "STAGING_SERVER_USERNAME=${{ secrets.STAGING_SERVER_USERNAME }}" >> $GITHUB_ENV
+            echo "RAILS_STAGING_KEY=${{ secrets.RAILS_STAGING_KEY }}" >> $GITHUB_ENV
+          fi
+      - name: Deploy with capistrano
+        id: cap_deploy
+        run: |
+          echo "Start ssh agent if required"
+          if [ -z "$SSH_AUTH_SOCK" ] ; then
+            eval "$(ssh-agent -s)"
+            ssh-add
+          fi
+          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_OUTPUT
+          LAST_DEPLOY_TAG=$(git tag -l [0-9]*_$STAGE | tail -n 1)
+          AUTHORS=$(git log --oneline --format="%an" $LAST_DEPLOY_TAG..origin/$BRANCH | sort -u | tr '\n' ',' | sed 's/trike-deploy,//;s/,$//g')
+          if [ -z "$AUTHORS" ]; then
+            AUTHORS=$(git log --oneline --format="%an" | sed -n '1p')
+          fi
+          git config user.name "$AUTHORS"
+          echo "AUTHORS=$AUTHORS" >> $GITHUB_ENV
+          nix-shell --arg deploy true --run "./run_deploy.sh"
+      - name: Kill ssh-agent
+        if: always()
+        run: |
+          SSH_AGENT_PID=${{ steps.cap_deploy.outputs.SSH_AGENT_PID }}
+          kill $SSH_AGENT_PID
+      - name: Open PR to stable
+        if: github.ref == 'refs/heads/master'
+        run: |
+          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.ACTIONS_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls -d '{"head":"master","base":"stable","title":"Merge branch master into stable","body":"This PR is automatically generated by CI."}'
+          PR_URL=$(curl -sX GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.ACTIONS_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls\?head\=bellroy:master\&base\=stable | jq -r '.[0].html_url | select(length>0)')
+          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
+      - name: Post to Slack if deploy succeeds
+        if: github.ref == 'refs/heads/master'
+        # Pin to the v1.23.0 SHA
+        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
+        env:
+          SLACK_BOT_TOKEN: "${{ secrets.BELLROY_SLACK_TOKEN }}"
+        with:
+          channel-id: "${{ env.SLACK_CHANNEL_ID }}"
+          payload: |
+            {
+              "text": ":loudspeaker: *${{ env.AUTHORS }}* succesfully deployed to `staging`. Open PR: ${{ env.PR_URL }}"
+            }
